// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuNJbmCI3KsHW6q3ZeCoFAJ7sgK_qoO50',
    appId: '1:119597759074:web:806dc0214415e4f667af3b',
    messagingSenderId: '119597759074',
    projectId: 'useralbum-6c8c9',
    authDomain: 'useralbum-6c8c9.firebaseapp.com',
    storageBucket: 'useralbum-6c8c9.appspot.com',
    measurementId: 'G-VVNV6628RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgmgj0rgzgjdpnU4b-f3JLzEH9J9yfvxs',
    appId: '1:119597759074:android:16a4441575359e1267af3b',
    messagingSenderId: '119597759074',
    projectId: 'useralbum-6c8c9',
    storageBucket: 'useralbum-6c8c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRsatjHMTMqPtXyN5GFhuMsf2Ll6PgNLQ',
    appId: '1:119597759074:ios:712ee3c6297d8b5c67af3b',
    messagingSenderId: '119597759074',
    projectId: 'useralbum-6c8c9',
    storageBucket: 'useralbum-6c8c9.appspot.com',
    iosClientId: '119597759074-vrp04verng2u7uhheqhuq56qu6ecmqlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.useralbum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRsatjHMTMqPtXyN5GFhuMsf2Ll6PgNLQ',
    appId: '1:119597759074:ios:712ee3c6297d8b5c67af3b',
    messagingSenderId: '119597759074',
    projectId: 'useralbum-6c8c9',
    storageBucket: 'useralbum-6c8c9.appspot.com',
    iosClientId: '119597759074-vrp04verng2u7uhheqhuq56qu6ecmqlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.useralbum',
  );
}
